### ISSUE TITLE
Packaging required for netscape-bookmark-parser

### ISSUE THREAD

**Issue by jvalleroy** [shaarli/shaarli-pkg-debian#7]
This library (https://github.com/shaarli/netscape-bookmark-parser) is required by Shaarli v0.8.0.

**Comment by virtualtam** [comment]
Follow-up on https://github.com/shaarli/netscape-bookmark-parser/issues/28 , I'll start working on this over the weekend :)

**Comment by jvalleroy** [comment]
php-netscape-bookmark-parser package has been uploaded to Debian unstable:
https://tracker.debian.org/pkg/php-netscape-bookmark-parser
