### ISSUE TITLE
Package Shaarli for Debian/FreedomBox

### ISSUE THREAD

**Issue by nodiscc** [shaarli/shaarli-pkg-debian#8]
@jvalleroy had started [packaging work](https://github.com/shaarli/shaarli-pkg-debian/commits/master) to get Shaarli in Debian and @freedombox. This work is now stale, if someone is interested in picking up the package maintenance, the following links may be useful:

- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864559 ITP for Shaarli
- https://tracker.debian.org/pkg/php-netscape-bookmark-parser (dependency for shaarli, already in Debian, see https://github.com/shaarli/shaarli-pkg-debian/issues/7)
- https://wiki.debian.org/FreedomBox/Manual/Shaarli Shaarli Freedombox user manual draft.

**Comment by jvalleroy** [comment]
I'm currently working on packaging the new dependencies for latest Shaarli. Any help is appreciated.
- https://wiki.debian.org/FreedomBox/Contribute/Packaging/Shaarli Packaging tasks
